source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12'

target "BasicExample" do
  use_frameworks!

  pod 'AssemblyGoogleIMAAdapter', :path => './'
end

target 'AssemblyGoogleIMAAdapter' do
  pod 'GoogleAds-IMA-iOS-SDK', '3.5.2'
end
